kind: Deployment
apiVersion: apps/v1
metadata:
   name: cluster-ip-service-another
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod1
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: nginx
          ports:
          - containerPort: 80
        - name: c001
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-world; sleep 5 ; done"]
